// Code generated by ogen, DO NOT EDIT.

package api

type BearerSchema struct {
	Token string
	Roles []string
}

// GetToken returns the value of Token.
func (s *BearerSchema) GetToken() string {
	return s.Token
}

// GetRoles returns the value of Roles.
func (s *BearerSchema) GetRoles() []string {
	return s.Roles
}

// SetToken sets the value of Token.
func (s *BearerSchema) SetToken(val string) {
	s.Token = val
}

// SetRoles sets the value of Roles.
func (s *BearerSchema) SetRoles(val []string) {
	s.Roles = val
}

type DpopProof struct {
	APIKey string
	Roles  []string
}

// GetAPIKey returns the value of APIKey.
func (s *DpopProof) GetAPIKey() string {
	return s.APIKey
}

// GetRoles returns the value of Roles.
func (s *DpopProof) GetRoles() []string {
	return s.Roles
}

// SetAPIKey sets the value of APIKey.
func (s *DpopProof) SetAPIKey(val string) {
	s.APIKey = val
}

// SetRoles sets the value of Roles.
func (s *DpopProof) SetRoles(val []string) {
	s.Roles = val
}

type DpopSchema struct {
	APIKey string
	Roles  []string
}

// GetAPIKey returns the value of APIKey.
func (s *DpopSchema) GetAPIKey() string {
	return s.APIKey
}

// GetRoles returns the value of Roles.
func (s *DpopSchema) GetRoles() []string {
	return s.Roles
}

// SetAPIKey sets the value of APIKey.
func (s *DpopSchema) SetAPIKey(val string) {
	s.APIKey = val
}

// SetRoles sets the value of Roles.
func (s *DpopSchema) SetRoles(val []string) {
	s.Roles = val
}

// OnboardForbidden is response for Onboard operation.
type OnboardForbidden struct{}

func (*OnboardForbidden) onboardRes() {}

// OnboardOK is response for Onboard operation.
type OnboardOK struct{}

func (*OnboardOK) onboardRes() {}

// OnboardUnauthorized is response for Onboard operation.
type OnboardUnauthorized struct{}

func (*OnboardUnauthorized) onboardRes() {}

// Specification on which namespace to create.
// Ref: #/components/schemas/OnboardingRequest
type OnboardingRequest struct {
	Group OptString `json:"group"`
}

// GetGroup returns the value of Group.
func (s *OnboardingRequest) GetGroup() OptString {
	return s.Group
}

// SetGroup sets the value of Group.
func (s *OnboardingRequest) SetGroup(val OptString) {
	s.Group = val
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}
