// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"
)

type Bearer struct {
	Token string
	Roles []string
}

// GetToken returns the value of Token.
func (s *Bearer) GetToken() string {
	return s.Token
}

// GetRoles returns the value of Roles.
func (s *Bearer) GetRoles() []string {
	return s.Roles
}

// SetToken sets the value of Token.
func (s *Bearer) SetToken(val string) {
	s.Token = val
}

// SetRoles sets the value of Roles.
func (s *Bearer) SetRoles(val []string) {
	s.Roles = val
}

type Dpop struct {
	Request *http.Request
	Roles   []string
}

// GetRequest returns the value of Request.
func (s *Dpop) GetRequest() *http.Request {
	return s.Request
}

// GetRoles returns the value of Roles.
func (s *Dpop) GetRoles() []string {
	return s.Roles
}

// SetRequest sets the value of Request.
func (s *Dpop) SetRequest(val *http.Request) {
	s.Request = val
}

// SetRoles sets the value of Roles.
func (s *Dpop) SetRoles(val []string) {
	s.Roles = val
}

// OnboardForbidden is response for Onboard operation.
type OnboardForbidden struct{}

func (*OnboardForbidden) onboardRes() {}

// OnboardOK is response for Onboard operation.
type OnboardOK struct{}

func (*OnboardOK) onboardRes() {}

// OnboardUnauthorized is response for Onboard operation.
type OnboardUnauthorized struct{}

func (*OnboardUnauthorized) onboardRes() {}

// Specification on which namespace to create.
// Ref: #/components/schemas/OnboardingRequest
type OnboardingRequest struct {
	Group OptString `json:"group"`
}

// GetGroup returns the value of Group.
func (s *OnboardingRequest) GetGroup() OptString {
	return s.Group
}

// SetGroup sets the value of Group.
func (s *OnboardingRequest) SetGroup(val OptString) {
	s.Group = val
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}
