// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
	"net/http"
	"strings"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/ogenerrors"
)

// SecurityHandler is handler for security parameters.
type SecurityHandler interface {
	// HandleBearer handles bearer security.
	// OAuth2 access token in Authorization header using the Bearer scheme.
	HandleBearer(ctx context.Context, operationName OperationName, t Bearer) (context.Context, error)
	// HandleDpop handles dpop security.
	// OAuth2 DPoP-bound access token sent in the Authorization header using the "DPoP" scheme. When
	// using this scheme, clients must also send a per-request "Dpop" proof header (RFC 9449).
	HandleDpop(ctx context.Context, operationName OperationName, t Dpop) (context.Context, error)
}

func findAuthorization(h http.Header, prefix string) (string, bool) {
	v, ok := h["Authorization"]
	if !ok {
		return "", false
	}
	for _, vv := range v {
		scheme, value, ok := strings.Cut(vv, " ")
		if !ok || !strings.EqualFold(scheme, prefix) {
			continue
		}
		return value, true
	}
	return "", false
}

var operationRolesBearer = map[string][]string{
	OnboardOperation: {},
}

func (s *Server) securityBearer(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t Bearer
	token, ok := findAuthorization(req.Header, "Bearer")
	if !ok {
		return ctx, false, nil
	}
	t.Token = token
	t.Roles = operationRolesBearer[operationName]
	rctx, err := s.sec.HandleBearer(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

var operationRolesDpop = map[string][]string{
	OnboardOperation: {},
}

func (s *Server) securityDpop(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t Dpop
	t.Request = req
	t.Roles = operationRolesDpop[operationName]
	rctx, err := s.sec.HandleDpop(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// Bearer provides bearer security value.
	// OAuth2 access token in Authorization header using the Bearer scheme.
	Bearer(ctx context.Context, operationName OperationName) (Bearer, error)
	// Dpop provides dpop security value.
	// OAuth2 DPoP-bound access token sent in the Authorization header using the "DPoP" scheme. When
	// using this scheme, clients must also send a per-request "Dpop" proof header (RFC 9449).
	Dpop(ctx context.Context, operationName OperationName, req *http.Request) error
}

func (s *Client) securityBearer(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.Bearer(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"Bearer\"")
	}
	req.Header.Set("Authorization", "Bearer "+t.Token)
	return nil
}
func (s *Client) securityDpop(ctx context.Context, operationName OperationName, req *http.Request) error {
	if err := s.sec.Dpop(ctx, operationName, req); err != nil {
		return errors.Wrap(err, "security source \"Dpop\"")
	}
	return nil
}
