// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	DeleteServiceOperation       OperationName = "DeleteService"
	GetMyCatalogsOperation       OperationName = "GetMyCatalogs"
	GetMyPackageOperation        OperationName = "GetMyPackage"
	GetPackageSchemaOperation    OperationName = "GetPackageSchema"
	GetServiceOperation          OperationName = "GetService"
	InstallServiceOperation      OperationName = "InstallService"
	ListServicesOperation        OperationName = "ListServices"
	SetServiceSuspendedOperation OperationName = "SetServiceSuspended"
	WatchReleaseOperation        OperationName = "WatchRelease"
	WatchResourcesOperation      OperationName = "WatchResources"
)
