// Code generated by ogen, DO NOT EDIT.
package api

type DeleteServiceRes interface {
	deleteServiceRes()
}

type GetMyCatalogsRes interface {
	getMyCatalogsRes()
}

type GetMyPackageRes interface {
	getMyPackageRes()
}

type GetPackageSchemaRes interface {
	getPackageSchemaRes()
}

type InstallServiceRes interface {
	installServiceRes()
}

type ResumeServiceRes interface {
	resumeServiceRes()
}

type SuspendServiceRes interface {
	suspendServiceRes()
}

type WatchReleaseRes interface {
	watchReleaseRes()
}

type WatchResourcesRes interface {
	watchResourcesRes()
}
