// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	GetMyCatalogsOperation                                            OperationName = "GetMyCatalogs"
	GetMyPackageOperation                                             OperationName = "GetMyPackage"
	InstallServiceOperation                                           OperationName = "InstallService"
	SchemasCatalogIdPackageNamePackageNameVersionsVersionGetOperation OperationName = "SchemasCatalogIdPackageNamePackageNameVersionsVersionGet"
	WatchReleaseOperation                                             OperationName = "WatchRelease"
	WatchResourcesOperation                                           OperationName = "WatchResources"
)
