// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// DeleteService implements deleteService operation.
	//
	// Runs helm uninstall for the release and removes the associated Onyxia secret. This operation is
	// irreversible.
	//
	// DELETE /api/services/{releaseId}
	DeleteService(ctx context.Context, params DeleteServiceParams) (DeleteServiceRes, error)
	// GetMyCatalogs implements getMyCatalogs operation.
	//
	// Returns the list of catalogs and packages available for the user. The list of packages is filtered
	// by user permissions if the user is authenticated. Otherwise returns the public catalog.
	//
	// GET /api/services/catalogs
	GetMyCatalogs(ctx context.Context) (GetMyCatalogsRes, error)
	// GetMyPackage implements getMyPackage operation.
	//
	// Returns detailed information about a package in a catalog, including available versions.
	//
	// GET /api/services/catalogs/{catalogId}/packages/{packageName}
	GetMyPackage(ctx context.Context, params GetMyPackageParams) (GetMyPackageRes, error)
	// GetPackageSchema implements getPackageSchema operation.
	//
	// Returns the values.schema.json of a versioned package. The schema is enhanced by user permissions
	// and roles.
	//
	// GET /api/services/catalogs/{catalogId}/packages/{packageName}/versions/{version}/schema
	GetPackageSchema(ctx context.Context, params GetPackageSchemaParams) (GetPackageSchemaRes, error)
	// GetProjectQuota implements getProjectQuota operation.
	//
	// Initial load only: while a service changes, its event stream pushes the quota updates.
	//
	// GET /api/services/project/quota
	GetProjectQuota(ctx context.Context, params GetProjectQuotaParams) (GetProjectQuotaRes, error)
	// GetService implements getService operation.
	//
	// Get the current state of a service.
	//
	// GET /api/services/{releaseId}
	GetService(ctx context.Context, params GetServiceParams) (GetServiceRes, error)
	// InstallService implements installService operation.
	//
	// Starts an install for the given releaseId and returns 202 as soon as the package is resolved; the
	// install goes on in the background. Follow it with the service's event stream (watchServiceEvents).
	// The releaseId is reserved by the first install: a second install with the same releaseId gets 409,
	// whether the first one is still running or done.
	//
	// PUT /api/services/{releaseId}
	InstallService(ctx context.Context, req *ServiceInstallRequest, params InstallServiceParams) (InstallServiceRes, error)
	// ListServices implements listServices operation.
	//
	// List all services in a project namespace.
	//
	// GET /api/services
	ListServices(ctx context.Context, params ListServicesParams) (ListServicesRes, error)
	// SetServiceShared implements setServiceShared operation.
	//
	// Only the owner of the service may change this flag. Sharing requires the service's catalog to allow
	// it.
	//
	// PUT /api/services/{releaseId}/shared
	SetServiceShared(ctx context.Context, req *SetServiceSharedReq, params SetServiceSharedParams) (SetServiceSharedRes, error)
	// SetServiceSuspended implements setServiceSuspended operation.
	//
	// Returns once the release is updated; its pods then stop or start in the background (Suspending,
	// Deploying). Follow it with the service's event stream (watchServiceEvents).
	//
	// PUT /api/services/{releaseId}/suspended
	SetServiceSuspended(ctx context.Context, req *SetServiceSuspendedReq, params SetServiceSuspendedParams) (SetServiceSuspendedRes, error)
	// WatchServiceEvents implements watchServiceEvents operation.
	//
	// Server-Sent Events (text/event-stream), one frame per event: "event: \ndata: \n\n" (see
	// ServiceStreamEvent for the payload of each event). Open it after an install, suspend, resume or
	// delete, or when showing a service in a transitional status.
	//
	//  - The first event is a "status" with the current state, and a "quota" with the project's quota when
	//    there is one. A reconnection simply starts again from the current state: there is no event id to
	//    resume from.
	//  - Then "status" is sent each time the service changes, "progress" for each step Kubernetes reports
	//    (scheduling, image pull, start, probe failure...), and "quota" each time the project's quota
	//    usage changes.
	//  - The server ends the stream with "done" once the service is stable (Running, Suspended, Ghost, an
	//    Error with reason release_failed), deleted, or after a maximum duration. Any other Error keeps
	//    the stream open: a crash loop or an exceeded quota can resolve by itself.
	//  - A comment line (": keep-alive") is sent periodically so that proxies keep the connection open.
	//
	// The browser's native EventSource can't send the Authorization and X-Onyxia-Project headers: use a
	// fetch-based SSE client.
	//
	// GET /api/services/{releaseId}/events
	WatchServiceEvents(ctx context.Context, params WatchServiceEventsParams) (WatchServiceEventsRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
