// Code generated by ogen, DO NOT EDIT.
package api

type DeleteServiceRes interface {
	deleteServiceRes()
}

type GetMyCatalogsRes interface {
	getMyCatalogsRes()
}

type GetMyPackageRes interface {
	getMyPackageRes()
}

type GetPackageSchemaRes interface {
	getPackageSchemaRes()
}

type GetServiceRes interface {
	getServiceRes()
}

type InstallServiceRes interface {
	installServiceRes()
}

type ListServicesRes interface {
	listServicesRes()
}

type SetServiceSuspendedRes interface {
	setServiceSuspendedRes()
}

type WatchReleaseRes interface {
	watchReleaseRes()
}

type WatchResourcesRes interface {
	watchResourcesRes()
}
