// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"
	"net/url"
	"strings"

	"github.com/ogen-go/ogen/uri"
)

var (
	rn12AllowedHeaders = map[string]string{
		"GET": "Authorization,X-Onyxia-Project",
	}
	rn3AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn7AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn10AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn11AllowedHeaders = map[string]string{
		"GET": "Authorization,X-Onyxia-Project",
	}
	rn2AllowedHeaders = map[string]string{
		"DELETE": "Authorization,X-Onyxia-Project",
		"GET":    "Authorization,X-Onyxia-Project",
		"PUT":    "Authorization,Content-Type,X-Onyxia-Project",
	}
	rn17AllowedHeaders = map[string]string{
		"GET": "Authorization,X-Onyxia-Project",
	}
	rn13AllowedHeaders = map[string]string{
		"PUT": "Authorization,Content-Type,X-Onyxia-Project",
	}
	rn15AllowedHeaders = map[string]string{
		"PUT": "Authorization,Content-Type,X-Onyxia-Project",
	}
)

func (s *Server) cutPrefix(path string) (string, bool) {
	prefix := s.cfg.Prefix
	if prefix == "" {
		return path, true
	}
	if !strings.HasPrefix(path, prefix) {
		// Prefix doesn't match.
		return "", false
	}
	// Cut prefix from the path.
	return strings.TrimPrefix(path, prefix), true
}

// ServeHTTP serves http request as defined by OpenAPI v3 specification,
// calling handler that matches the path or returning not found error.
func (s *Server) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	elem := r.URL.Path
	elemIsEscaped := false
	if rawPath := r.URL.RawPath; rawPath != "" {
		if normalized, ok := uri.NormalizeEscapedPath(rawPath); ok {
			elem = normalized
			elemIsEscaped = strings.ContainsRune(elem, '%')
		}
	}

	elem, ok := s.cutPrefix(elem)
	if !ok || len(elem) == 0 {
		s.notFound(w, r)
		return
	}
	args := [3]string{}

	// Static code generated router with unwrapped path search.
	switch {
	default:
		if len(elem) == 0 {
			break
		}
		switch elem[0] {
		case '/': // Prefix: "/api/services"

			if l := len("/api/services"); len(elem) >= l && elem[0:l] == "/api/services" {
				elem = elem[l:]
			} else {
				break
			}

			if len(elem) == 0 {
				switch r.Method {
				case "GET":
					s.handleListServicesRequest([0]string{}, elemIsEscaped, w, r)
				default:
					s.notAllowed(w, r, notAllowedParams{
						allowedMethods: "GET",
						allowedHeaders: rn12AllowedHeaders,
						acceptPost:     "",
						acceptPatch:    "",
					})
				}

				return
			}
			switch elem[0] {
			case '/': // Prefix: "/"

				if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'c': // Prefix: "catalogs"
					origElem := elem
					if l := len("catalogs"); len(elem) >= l && elem[0:l] == "catalogs" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						switch r.Method {
						case "GET":
							s.handleGetMyCatalogsRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "GET",
								allowedHeaders: rn3AllowedHeaders,
								acceptPost:     "",
								acceptPatch:    "",
							})
						}

						return
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "catalogId"
						// Match until "/"
						idx := strings.IndexByte(elem, '/')
						if idx < 0 {
							idx = len(elem)
						}
						args[0] = elem[:idx]
						elem = elem[idx:]

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case '/': // Prefix: "/packages/"

							if l := len("/packages/"); len(elem) >= l && elem[0:l] == "/packages/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "packageName"
							// Match until "/"
							idx := strings.IndexByte(elem, '/')
							if idx < 0 {
								idx = len(elem)
							}
							args[1] = elem[:idx]
							elem = elem[idx:]

							if len(elem) == 0 {
								switch r.Method {
								case "GET":
									s.handleGetMyPackageRequest([2]string{
										args[0],
										args[1],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "GET",
										allowedHeaders: rn7AllowedHeaders,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}
							switch elem[0] {
							case '/': // Prefix: "/versions/"

								if l := len("/versions/"); len(elem) >= l && elem[0:l] == "/versions/" {
									elem = elem[l:]
								} else {
									break
								}

								// Param: "version"
								// Match until "/"
								idx := strings.IndexByte(elem, '/')
								if idx < 0 {
									idx = len(elem)
								}
								args[2] = elem[:idx]
								elem = elem[idx:]

								if len(elem) == 0 {
									break
								}
								switch elem[0] {
								case '/': // Prefix: "/schema"

									if l := len("/schema"); len(elem) >= l && elem[0:l] == "/schema" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										// Leaf node.
										switch r.Method {
										case "GET":
											s.handleGetPackageSchemaRequest([3]string{
												args[0],
												args[1],
												args[2],
											}, elemIsEscaped, w, r)
										default:
											s.notAllowed(w, r, notAllowedParams{
												allowedMethods: "GET",
												allowedHeaders: rn10AllowedHeaders,
												acceptPost:     "",
												acceptPatch:    "",
											})
										}

										return
									}

								}

							}

						}

					}

					elem = origElem
				case 'p': // Prefix: "project/quota"
					origElem := elem
					if l := len("project/quota"); len(elem) >= l && elem[0:l] == "project/quota" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "GET":
							s.handleGetProjectQuotaRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "GET",
								allowedHeaders: rn11AllowedHeaders,
								acceptPost:     "",
								acceptPatch:    "",
							})
						}

						return
					}

					elem = origElem
				}
				// Param: "releaseId"
				// Match until "/"
				idx := strings.IndexByte(elem, '/')
				if idx < 0 {
					idx = len(elem)
				}
				args[0] = elem[:idx]
				elem = elem[idx:]

				if len(elem) == 0 {
					switch r.Method {
					case "DELETE":
						s.handleDeleteServiceRequest([1]string{
							args[0],
						}, elemIsEscaped, w, r)
					case "GET":
						s.handleGetServiceRequest([1]string{
							args[0],
						}, elemIsEscaped, w, r)
					case "PUT":
						s.handleInstallServiceRequest([1]string{
							args[0],
						}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, notAllowedParams{
							allowedMethods: "DELETE,GET,PUT",
							allowedHeaders: rn2AllowedHeaders,
							acceptPost:     "",
							acceptPatch:    "",
						})
					}

					return
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'e': // Prefix: "events"

						if l := len("events"); len(elem) >= l && elem[0:l] == "events" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "GET":
								s.handleWatchServiceEventsRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "GET",
									allowedHeaders: rn17AllowedHeaders,
									acceptPost:     "",
									acceptPatch:    "",
								})
							}

							return
						}

					case 's': // Prefix: "s"

						if l := len("s"); len(elem) >= l && elem[0:l] == "s" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'h': // Prefix: "hared"

							if l := len("hared"); len(elem) >= l && elem[0:l] == "hared" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "PUT":
									s.handleSetServiceSharedRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "PUT",
										allowedHeaders: rn13AllowedHeaders,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}

						case 'u': // Prefix: "uspended"

							if l := len("uspended"); len(elem) >= l && elem[0:l] == "uspended" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "PUT":
									s.handleSetServiceSuspendedRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "PUT",
										allowedHeaders: rn15AllowedHeaders,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}

						}

					}

				}

			}

		}
	}
	s.notFound(w, r)
}

// Route is route object.
type Route struct {
	name           string
	summary        string
	operationID    string
	operationGroup string
	pathPattern    string
	count          int
	args           [3]string
}

// Name returns ogen operation name.
//
// It is guaranteed to be unique and not empty.
func (r Route) Name() string {
	return r.name
}

// Summary returns OpenAPI summary.
func (r Route) Summary() string {
	return r.summary
}

// OperationID returns OpenAPI operationId.
func (r Route) OperationID() string {
	return r.operationID
}

// OperationGroup returns the x-ogen-operation-group value.
func (r Route) OperationGroup() string {
	return r.operationGroup
}

// PathPattern returns OpenAPI path.
func (r Route) PathPattern() string {
	return r.pathPattern
}

// Args returns parsed arguments.
func (r Route) Args() []string {
	return r.args[:r.count]
}

// FindRoute finds Route for given method and path.
//
// Note: this method does not unescape path or handle reserved characters in path properly. Use FindPath instead.
func (s *Server) FindRoute(method, path string) (Route, bool) {
	return s.FindPath(method, &url.URL{Path: path})
}

// FindPath finds Route for given method and URL.
func (s *Server) FindPath(method string, u *url.URL) (r Route, _ bool) {
	var (
		elem = u.Path
		args = r.args
	)
	if rawPath := u.RawPath; rawPath != "" {
		if normalized, ok := uri.NormalizeEscapedPath(rawPath); ok {
			elem = normalized
		}
		defer func() {
			for i, arg := range r.args[:r.count] {
				if unescaped, err := url.PathUnescape(arg); err == nil {
					r.args[i] = unescaped
				}
			}
		}()
	}

	elem, ok := s.cutPrefix(elem)
	if !ok {
		return r, false
	}

	// Static code generated router with unwrapped path search.
	switch {
	default:
		if len(elem) == 0 {
			break
		}
		switch elem[0] {
		case '/': // Prefix: "/api/services"

			if l := len("/api/services"); len(elem) >= l && elem[0:l] == "/api/services" {
				elem = elem[l:]
			} else {
				break
			}

			if len(elem) == 0 {
				switch method {
				case "GET":
					r.name = ListServicesOperation
					r.summary = "List all services in a project namespace"
					r.operationID = "listServices"
					r.operationGroup = ""
					r.pathPattern = "/api/services"
					r.args = args
					r.count = 0
					return r, true
				default:
					return
				}
			}
			switch elem[0] {
			case '/': // Prefix: "/"

				if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'c': // Prefix: "catalogs"
					origElem := elem
					if l := len("catalogs"); len(elem) >= l && elem[0:l] == "catalogs" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						switch method {
						case "GET":
							r.name = GetMyCatalogsOperation
							r.summary = "List available catalogs and packages for installing for the user"
							r.operationID = "getMyCatalogs"
							r.operationGroup = ""
							r.pathPattern = "/api/services/catalogs"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "catalogId"
						// Match until "/"
						idx := strings.IndexByte(elem, '/')
						if idx < 0 {
							idx = len(elem)
						}
						args[0] = elem[:idx]
						elem = elem[idx:]

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case '/': // Prefix: "/packages/"

							if l := len("/packages/"); len(elem) >= l && elem[0:l] == "/packages/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "packageName"
							// Match until "/"
							idx := strings.IndexByte(elem, '/')
							if idx < 0 {
								idx = len(elem)
							}
							args[1] = elem[:idx]
							elem = elem[idx:]

							if len(elem) == 0 {
								switch method {
								case "GET":
									r.name = GetMyPackageOperation
									r.summary = "Get detailed information about a package in a catalog"
									r.operationID = "getMyPackage"
									r.operationGroup = ""
									r.pathPattern = "/api/services/catalogs/{catalogId}/packages/{packageName}"
									r.args = args
									r.count = 2
									return r, true
								default:
									return
								}
							}
							switch elem[0] {
							case '/': // Prefix: "/versions/"

								if l := len("/versions/"); len(elem) >= l && elem[0:l] == "/versions/" {
									elem = elem[l:]
								} else {
									break
								}

								// Param: "version"
								// Match until "/"
								idx := strings.IndexByte(elem, '/')
								if idx < 0 {
									idx = len(elem)
								}
								args[2] = elem[:idx]
								elem = elem[idx:]

								if len(elem) == 0 {
									break
								}
								switch elem[0] {
								case '/': // Prefix: "/schema"

									if l := len("/schema"); len(elem) >= l && elem[0:l] == "/schema" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										// Leaf node.
										switch method {
										case "GET":
											r.name = GetPackageSchemaOperation
											r.summary = "Get the values.schema.json of a versioned package"
											r.operationID = "getPackageSchema"
											r.operationGroup = ""
											r.pathPattern = "/api/services/catalogs/{catalogId}/packages/{packageName}/versions/{version}/schema"
											r.args = args
											r.count = 3
											return r, true
										default:
											return
										}
									}

								}

							}

						}

					}

					elem = origElem
				case 'p': // Prefix: "project/quota"
					origElem := elem
					if l := len("project/quota"); len(elem) >= l && elem[0:l] == "project/quota" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "GET":
							r.name = GetProjectQuotaOperation
							r.summary = "Get the resource quota of the project and its usage"
							r.operationID = "getProjectQuota"
							r.operationGroup = ""
							r.pathPattern = "/api/services/project/quota"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}

					elem = origElem
				}
				// Param: "releaseId"
				// Match until "/"
				idx := strings.IndexByte(elem, '/')
				if idx < 0 {
					idx = len(elem)
				}
				args[0] = elem[:idx]
				elem = elem[idx:]

				if len(elem) == 0 {
					switch method {
					case "DELETE":
						r.name = DeleteServiceOperation
						r.summary = "Uninstall a service"
						r.operationID = "deleteService"
						r.operationGroup = ""
						r.pathPattern = "/api/services/{releaseId}"
						r.args = args
						r.count = 1
						return r, true
					case "GET":
						r.name = GetServiceOperation
						r.summary = "Get the current state of a service"
						r.operationID = "getService"
						r.operationGroup = ""
						r.pathPattern = "/api/services/{releaseId}"
						r.args = args
						r.count = 1
						return r, true
					case "PUT":
						r.name = InstallServiceOperation
						r.summary = "Trigger service installation (async)"
						r.operationID = "installService"
						r.operationGroup = ""
						r.pathPattern = "/api/services/{releaseId}"
						r.args = args
						r.count = 1
						return r, true
					default:
						return
					}
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'e': // Prefix: "events"

						if l := len("events"); len(elem) >= l && elem[0:l] == "events" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "GET":
								r.name = WatchServiceEventsOperation
								r.summary = "Follow a service while it changes (SSE)"
								r.operationID = "watchServiceEvents"
								r.operationGroup = ""
								r.pathPattern = "/api/services/{releaseId}/events"
								r.args = args
								r.count = 1
								return r, true
							default:
								return
							}
						}

					case 's': // Prefix: "s"

						if l := len("s"); len(elem) >= l && elem[0:l] == "s" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'h': // Prefix: "hared"

							if l := len("hared"); len(elem) >= l && elem[0:l] == "hared" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "PUT":
									r.name = SetServiceSharedOperation
									r.summary = "Share or unshare a service with the project members"
									r.operationID = "setServiceShared"
									r.operationGroup = ""
									r.pathPattern = "/api/services/{releaseId}/shared"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

						case 'u': // Prefix: "uspended"

							if l := len("uspended"); len(elem) >= l && elem[0:l] == "uspended" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "PUT":
									r.name = SetServiceSuspendedOperation
									r.summary = "Suspend or resume a service"
									r.operationID = "setServiceSuspended"
									r.operationGroup = ""
									r.pathPattern = "/api/services/{releaseId}/suspended"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

						}

					}

				}

			}

		}
	}
	return r, false
}
