// Code generated by ogen, DO NOT EDIT.
package api

type GetMyCatalogsRes interface {
	getMyCatalogsRes()
}

type InstallServiceRes interface {
	installServiceRes()
}

type WatchReleaseRes interface {
	watchReleaseRes()
}

type WatchResourcesRes interface {
	watchResourcesRes()
}
