// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
	"io"
	"net/url"
	"strings"
	"time"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/conv"
	ht "github.com/ogen-go/ogen/http"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/otelogen"
	"github.com/ogen-go/ogen/uri"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/metric"
	semconv "go.opentelemetry.io/otel/semconv/v1.39.0"
	"go.opentelemetry.io/otel/trace"
)

func trimTrailingSlashes(u *url.URL) {
	u.Path = strings.TrimRight(u.Path, "/")
	u.RawPath = strings.TrimRight(u.RawPath, "/")
}

// Invoker invokes operations described by OpenAPI v3 specification.
type Invoker interface {
	// DeleteService invokes deleteService operation.
	//
	// Runs helm uninstall for the release and removes the associated Onyxia secret. This operation is
	// irreversible.
	//
	// DELETE /api/services/{releaseId}
	DeleteService(ctx context.Context, params DeleteServiceParams) (DeleteServiceRes, error)
	// GetMyCatalogs invokes getMyCatalogs operation.
	//
	// Returns the list of catalogs and packages available for the user. The list of packages is filtered
	// by user permissions if the user is authenticated. Otherwise returns the public catalog.
	//
	// GET /api/services/catalogs
	GetMyCatalogs(ctx context.Context) (GetMyCatalogsRes, error)
	// GetMyPackage invokes getMyPackage operation.
	//
	// Returns detailed information about a package in a catalog, including available versions.
	//
	// GET /api/services/catalogs/{catalogId}/packages/{packageName}
	GetMyPackage(ctx context.Context, params GetMyPackageParams) (GetMyPackageRes, error)
	// GetPackageSchema invokes getPackageSchema operation.
	//
	// Returns the values.schema.json of a versioned package. The schema is enhanced by user permissions
	// and roles.
	//
	// GET /api/services/catalogs/{catalogId}/packages/{packageName}/versions/{version}/schema
	GetPackageSchema(ctx context.Context, params GetPackageSchemaParams) (GetPackageSchemaRes, error)
	// GetProjectQuota invokes getProjectQuota operation.
	//
	// Initial load only: while a service changes, its event stream pushes the quota updates.
	//
	// GET /api/services/project/quota
	GetProjectQuota(ctx context.Context, params GetProjectQuotaParams) (GetProjectQuotaRes, error)
	// GetService invokes getService operation.
	//
	// Get the current state of a service.
	//
	// GET /api/services/{releaseId}
	GetService(ctx context.Context, params GetServiceParams) (GetServiceRes, error)
	// InstallService invokes installService operation.
	//
	// Starts an install for the given releaseId and returns 202 as soon as the package is resolved; the
	// install goes on in the background. Follow it with the service's event stream (watchServiceEvents).
	// The releaseId is reserved by the first install: a second install with the same releaseId gets 409,
	// whether the first one is still running or done.
	//
	// PUT /api/services/{releaseId}
	InstallService(ctx context.Context, request *ServiceInstallRequest, params InstallServiceParams) (InstallServiceRes, error)
	// ListServices invokes listServices operation.
	//
	// List all services in a project namespace.
	//
	// GET /api/services
	ListServices(ctx context.Context, params ListServicesParams) (ListServicesRes, error)
	// SetServiceShared invokes setServiceShared operation.
	//
	// Only the owner of the service may change this flag. Sharing requires the service's catalog to allow
	// it.
	//
	// PUT /api/services/{releaseId}/shared
	SetServiceShared(ctx context.Context, request *SetServiceSharedReq, params SetServiceSharedParams) (SetServiceSharedRes, error)
	// SetServiceSuspended invokes setServiceSuspended operation.
	//
	// Returns once the release is updated; its pods then stop or start in the background (Suspending,
	// Deploying). Follow it with the service's event stream (watchServiceEvents).
	//
	// PUT /api/services/{releaseId}/suspended
	SetServiceSuspended(ctx context.Context, request *SetServiceSuspendedReq, params SetServiceSuspendedParams) (SetServiceSuspendedRes, error)
	// WatchServiceEvents invokes watchServiceEvents operation.
	//
	// Server-Sent Events (text/event-stream), one frame per event: "event: \ndata: \n\n" (see
	// ServiceStreamEvent for the payload of each event). Open it after an install, suspend or resume,
	// before a delete (once deleted, the service can no longer be opened), or when showing a service in a
	// transitional status.
	//
	//  - The first event is a "status" with the current state, and a "quota" with the project's quota when
	//    there is one. A reconnection simply starts again from the current state: there is no event id to
	//    resume from.
	//  - Then "status" is sent each time the service changes, "progress" for each step Kubernetes reports
	//    (scheduling, image pull, start, probe failure...), and "quota" each time the project's quota
	//    usage changes.
	//  - The server ends the stream with "done" once the service is stable (Running, Suspended, an Error
	//    with reason release_failed, or a Ghost that lasts: the release of a starting install appears a
	//    moment after the service), deleted (no pod left), or after a maximum duration (15 minutes). Any
	//    other Error keeps the stream open: a crash loop or an exceeded quota can resolve by itself.
	//  - The stream may also end without "done" (server shutdown, broken watch): reopen it.
	//  - A comment line (": keep-alive") is sent periodically so that proxies keep the connection open.
	//
	// The browser's native EventSource can't send the Authorization and X-Onyxia-Project headers: use a
	// fetch-based SSE client.
	//
	// GET /api/services/{releaseId}/events
	WatchServiceEvents(ctx context.Context, params WatchServiceEventsParams) (WatchServiceEventsRes, error)
}

// Client implements OAS client.
type Client struct {
	serverURL *url.URL
	sec       SecuritySource
	baseClient
}

// NewClient initializes new Client defined by OAS.
func NewClient(serverURL string, sec SecuritySource, opts ...ClientOption) (*Client, error) {
	u, err := url.Parse(serverURL)
	if err != nil {
		return nil, err
	}
	trimTrailingSlashes(u)

	c, err := newClientConfig(opts...).baseClient()
	if err != nil {
		return nil, err
	}
	return &Client{
		serverURL:  u,
		sec:        sec,
		baseClient: c,
	}, nil
}

type serverURLKey struct{}

// WithServerURL sets context key to override server URL.
func WithServerURL(ctx context.Context, u *url.URL) context.Context {
	return context.WithValue(ctx, serverURLKey{}, u)
}

func (c *Client) requestURL(ctx context.Context) *url.URL {
	u, ok := ctx.Value(serverURLKey{}).(*url.URL)
	if !ok {
		return c.serverURL
	}
	return u
}

// DeleteService invokes deleteService operation.
//
// Runs helm uninstall for the release and removes the associated Onyxia secret. This operation is
// irreversible.
//
// DELETE /api/services/{releaseId}
func (c *Client) DeleteService(ctx context.Context, params DeleteServiceParams) (DeleteServiceRes, error) {
	res, err := c.sendDeleteService(ctx, params)
	return res, err
}

func (c *Client) sendDeleteService(ctx context.Context, params DeleteServiceParams) (res DeleteServiceRes, err error) {
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("deleteService"),
		semconv.HTTPRequestMethodKey.String("DELETE"),
		semconv.URLTemplateKey.String("/api/services/{releaseId}"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, DeleteServiceOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [2]string
	pathParts[0] = "/api/services/"
	{
		// Encode "releaseId" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "releaseId",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.ReleaseId))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "DELETE", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	stage = "EncodeHeaderParams"
	h := uri.NewHeaderEncoder(r.Header)
	{
		cfg := uri.HeaderParameterEncodingConfig{
			Name:    "X-Onyxia-Project",
			Explode: false,
		}
		if err := h.EncodeParam(cfg, func(e uri.Encoder) error {
			return e.EncodeValue(conv.StringToString(params.XOnyxiaProject))
		}); err != nil {
			return res, errors.Wrap(err, "encode header")
		}
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{
			stage = "Security:Oidc"
			switch err := c.securityOidc(ctx, DeleteServiceOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"Oidc\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer func() {
		// Drain the body to EOF before closing, so the underlying
		// connection can be reused by the Transport regardless of the
		// response status code. See https://github.com/ogen-go/ogen/issues/1670.
		_, _ = io.Copy(io.Discard, body)
		_ = body.Close()
	}()

	stage = "DecodeResponse"
	result, err := decodeDeleteServiceResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// GetMyCatalogs invokes getMyCatalogs operation.
//
// Returns the list of catalogs and packages available for the user. The list of packages is filtered
// by user permissions if the user is authenticated. Otherwise returns the public catalog.
//
// GET /api/services/catalogs
func (c *Client) GetMyCatalogs(ctx context.Context) (GetMyCatalogsRes, error) {
	res, err := c.sendGetMyCatalogs(ctx)
	return res, err
}

func (c *Client) sendGetMyCatalogs(ctx context.Context) (res GetMyCatalogsRes, err error) {
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("getMyCatalogs"),
		semconv.HTTPRequestMethodKey.String("GET"),
		semconv.URLTemplateKey.String("/api/services/catalogs"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, GetMyCatalogsOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/api/services/catalogs"
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{
			stage = "Security:Oidc"
			switch err := c.securityOidc(ctx, GetMyCatalogsOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"Oidc\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{},
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer func() {
		// Drain the body to EOF before closing, so the underlying
		// connection can be reused by the Transport regardless of the
		// response status code. See https://github.com/ogen-go/ogen/issues/1670.
		_, _ = io.Copy(io.Discard, body)
		_ = body.Close()
	}()

	stage = "DecodeResponse"
	result, err := decodeGetMyCatalogsResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// GetMyPackage invokes getMyPackage operation.
//
// Returns detailed information about a package in a catalog, including available versions.
//
// GET /api/services/catalogs/{catalogId}/packages/{packageName}
func (c *Client) GetMyPackage(ctx context.Context, params GetMyPackageParams) (GetMyPackageRes, error) {
	res, err := c.sendGetMyPackage(ctx, params)
	return res, err
}

func (c *Client) sendGetMyPackage(ctx context.Context, params GetMyPackageParams) (res GetMyPackageRes, err error) {
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("getMyPackage"),
		semconv.HTTPRequestMethodKey.String("GET"),
		semconv.URLTemplateKey.String("/api/services/catalogs/{catalogId}/packages/{packageName}"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, GetMyPackageOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [4]string
	pathParts[0] = "/api/services/catalogs/"
	{
		// Encode "catalogId" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "catalogId",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.CatalogId))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/packages/"
	{
		// Encode "packageName" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "packageName",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.PackageName))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[3] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{
			stage = "Security:Oidc"
			switch err := c.securityOidc(ctx, GetMyPackageOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"Oidc\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer func() {
		// Drain the body to EOF before closing, so the underlying
		// connection can be reused by the Transport regardless of the
		// response status code. See https://github.com/ogen-go/ogen/issues/1670.
		_, _ = io.Copy(io.Discard, body)
		_ = body.Close()
	}()

	stage = "DecodeResponse"
	result, err := decodeGetMyPackageResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// GetPackageSchema invokes getPackageSchema operation.
//
// Returns the values.schema.json of a versioned package. The schema is enhanced by user permissions
// and roles.
//
// GET /api/services/catalogs/{catalogId}/packages/{packageName}/versions/{version}/schema
func (c *Client) GetPackageSchema(ctx context.Context, params GetPackageSchemaParams) (GetPackageSchemaRes, error) {
	res, err := c.sendGetPackageSchema(ctx, params)
	return res, err
}

func (c *Client) sendGetPackageSchema(ctx context.Context, params GetPackageSchemaParams) (res GetPackageSchemaRes, err error) {
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("getPackageSchema"),
		semconv.HTTPRequestMethodKey.String("GET"),
		semconv.URLTemplateKey.String("/api/services/catalogs/{catalogId}/packages/{packageName}/versions/{version}/schema"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, GetPackageSchemaOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [7]string
	pathParts[0] = "/api/services/catalogs/"
	{
		// Encode "catalogId" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "catalogId",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.CatalogId))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/packages/"
	{
		// Encode "packageName" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "packageName",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.PackageName))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[3] = encoded
	}
	pathParts[4] = "/versions/"
	{
		// Encode "version" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "version",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.Version))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[5] = encoded
	}
	pathParts[6] = "/schema"
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{
			stage = "Security:Oidc"
			switch err := c.securityOidc(ctx, GetPackageSchemaOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"Oidc\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer func() {
		// Drain the body to EOF before closing, so the underlying
		// connection can be reused by the Transport regardless of the
		// response status code. See https://github.com/ogen-go/ogen/issues/1670.
		_, _ = io.Copy(io.Discard, body)
		_ = body.Close()
	}()

	stage = "DecodeResponse"
	result, err := decodeGetPackageSchemaResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// GetProjectQuota invokes getProjectQuota operation.
//
// Initial load only: while a service changes, its event stream pushes the quota updates.
//
// GET /api/services/project/quota
func (c *Client) GetProjectQuota(ctx context.Context, params GetProjectQuotaParams) (GetProjectQuotaRes, error) {
	res, err := c.sendGetProjectQuota(ctx, params)
	return res, err
}

func (c *Client) sendGetProjectQuota(ctx context.Context, params GetProjectQuotaParams) (res GetProjectQuotaRes, err error) {
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("getProjectQuota"),
		semconv.HTTPRequestMethodKey.String("GET"),
		semconv.URLTemplateKey.String("/api/services/project/quota"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, GetProjectQuotaOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/api/services/project/quota"
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	stage = "EncodeHeaderParams"
	h := uri.NewHeaderEncoder(r.Header)
	{
		cfg := uri.HeaderParameterEncodingConfig{
			Name:    "X-Onyxia-Project",
			Explode: false,
		}
		if err := h.EncodeParam(cfg, func(e uri.Encoder) error {
			return e.EncodeValue(conv.StringToString(params.XOnyxiaProject))
		}); err != nil {
			return res, errors.Wrap(err, "encode header")
		}
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{
			stage = "Security:Oidc"
			switch err := c.securityOidc(ctx, GetProjectQuotaOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"Oidc\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer func() {
		// Drain the body to EOF before closing, so the underlying
		// connection can be reused by the Transport regardless of the
		// response status code. See https://github.com/ogen-go/ogen/issues/1670.
		_, _ = io.Copy(io.Discard, body)
		_ = body.Close()
	}()

	stage = "DecodeResponse"
	result, err := decodeGetProjectQuotaResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// GetService invokes getService operation.
//
// Get the current state of a service.
//
// GET /api/services/{releaseId}
func (c *Client) GetService(ctx context.Context, params GetServiceParams) (GetServiceRes, error) {
	res, err := c.sendGetService(ctx, params)
	return res, err
}

func (c *Client) sendGetService(ctx context.Context, params GetServiceParams) (res GetServiceRes, err error) {
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("getService"),
		semconv.HTTPRequestMethodKey.String("GET"),
		semconv.URLTemplateKey.String("/api/services/{releaseId}"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, GetServiceOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [2]string
	pathParts[0] = "/api/services/"
	{
		// Encode "releaseId" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "releaseId",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.ReleaseId))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	stage = "EncodeHeaderParams"
	h := uri.NewHeaderEncoder(r.Header)
	{
		cfg := uri.HeaderParameterEncodingConfig{
			Name:    "X-Onyxia-Project",
			Explode: false,
		}
		if err := h.EncodeParam(cfg, func(e uri.Encoder) error {
			return e.EncodeValue(conv.StringToString(params.XOnyxiaProject))
		}); err != nil {
			return res, errors.Wrap(err, "encode header")
		}
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{
			stage = "Security:Oidc"
			switch err := c.securityOidc(ctx, GetServiceOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"Oidc\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer func() {
		// Drain the body to EOF before closing, so the underlying
		// connection can be reused by the Transport regardless of the
		// response status code. See https://github.com/ogen-go/ogen/issues/1670.
		_, _ = io.Copy(io.Discard, body)
		_ = body.Close()
	}()

	stage = "DecodeResponse"
	result, err := decodeGetServiceResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// InstallService invokes installService operation.
//
// Starts an install for the given releaseId and returns 202 as soon as the package is resolved; the
// install goes on in the background. Follow it with the service's event stream (watchServiceEvents).
// The releaseId is reserved by the first install: a second install with the same releaseId gets 409,
// whether the first one is still running or done.
//
// PUT /api/services/{releaseId}
func (c *Client) InstallService(ctx context.Context, request *ServiceInstallRequest, params InstallServiceParams) (InstallServiceRes, error) {
	res, err := c.sendInstallService(ctx, request, params)
	return res, err
}

func (c *Client) sendInstallService(ctx context.Context, request *ServiceInstallRequest, params InstallServiceParams) (res InstallServiceRes, err error) {
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("installService"),
		semconv.HTTPRequestMethodKey.String("PUT"),
		semconv.URLTemplateKey.String("/api/services/{releaseId}"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, InstallServiceOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [2]string
	pathParts[0] = "/api/services/"
	{
		// Encode "releaseId" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "releaseId",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.ReleaseId))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "PUT", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeInstallServiceRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	stage = "EncodeHeaderParams"
	h := uri.NewHeaderEncoder(r.Header)
	{
		cfg := uri.HeaderParameterEncodingConfig{
			Name:    "X-Onyxia-Project",
			Explode: false,
		}
		if err := h.EncodeParam(cfg, func(e uri.Encoder) error {
			return e.EncodeValue(conv.StringToString(params.XOnyxiaProject))
		}); err != nil {
			return res, errors.Wrap(err, "encode header")
		}
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{
			stage = "Security:Oidc"
			switch err := c.securityOidc(ctx, InstallServiceOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"Oidc\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer func() {
		// Drain the body to EOF before closing, so the underlying
		// connection can be reused by the Transport regardless of the
		// response status code. See https://github.com/ogen-go/ogen/issues/1670.
		_, _ = io.Copy(io.Discard, body)
		_ = body.Close()
	}()

	stage = "DecodeResponse"
	result, err := decodeInstallServiceResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// ListServices invokes listServices operation.
//
// List all services in a project namespace.
//
// GET /api/services
func (c *Client) ListServices(ctx context.Context, params ListServicesParams) (ListServicesRes, error) {
	res, err := c.sendListServices(ctx, params)
	return res, err
}

func (c *Client) sendListServices(ctx context.Context, params ListServicesParams) (res ListServicesRes, err error) {
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("listServices"),
		semconv.HTTPRequestMethodKey.String("GET"),
		semconv.URLTemplateKey.String("/api/services"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, ListServicesOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/api/services"
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	stage = "EncodeHeaderParams"
	h := uri.NewHeaderEncoder(r.Header)
	{
		cfg := uri.HeaderParameterEncodingConfig{
			Name:    "X-Onyxia-Project",
			Explode: false,
		}
		if err := h.EncodeParam(cfg, func(e uri.Encoder) error {
			return e.EncodeValue(conv.StringToString(params.XOnyxiaProject))
		}); err != nil {
			return res, errors.Wrap(err, "encode header")
		}
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{
			stage = "Security:Oidc"
			switch err := c.securityOidc(ctx, ListServicesOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"Oidc\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer func() {
		// Drain the body to EOF before closing, so the underlying
		// connection can be reused by the Transport regardless of the
		// response status code. See https://github.com/ogen-go/ogen/issues/1670.
		_, _ = io.Copy(io.Discard, body)
		_ = body.Close()
	}()

	stage = "DecodeResponse"
	result, err := decodeListServicesResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// SetServiceShared invokes setServiceShared operation.
//
// Only the owner of the service may change this flag. Sharing requires the service's catalog to allow
// it.
//
// PUT /api/services/{releaseId}/shared
func (c *Client) SetServiceShared(ctx context.Context, request *SetServiceSharedReq, params SetServiceSharedParams) (SetServiceSharedRes, error) {
	res, err := c.sendSetServiceShared(ctx, request, params)
	return res, err
}

func (c *Client) sendSetServiceShared(ctx context.Context, request *SetServiceSharedReq, params SetServiceSharedParams) (res SetServiceSharedRes, err error) {
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("setServiceShared"),
		semconv.HTTPRequestMethodKey.String("PUT"),
		semconv.URLTemplateKey.String("/api/services/{releaseId}/shared"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, SetServiceSharedOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [3]string
	pathParts[0] = "/api/services/"
	{
		// Encode "releaseId" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "releaseId",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.ReleaseId))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/shared"
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "PUT", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeSetServiceSharedRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	stage = "EncodeHeaderParams"
	h := uri.NewHeaderEncoder(r.Header)
	{
		cfg := uri.HeaderParameterEncodingConfig{
			Name:    "X-Onyxia-Project",
			Explode: false,
		}
		if err := h.EncodeParam(cfg, func(e uri.Encoder) error {
			return e.EncodeValue(conv.StringToString(params.XOnyxiaProject))
		}); err != nil {
			return res, errors.Wrap(err, "encode header")
		}
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{
			stage = "Security:Oidc"
			switch err := c.securityOidc(ctx, SetServiceSharedOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"Oidc\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer func() {
		// Drain the body to EOF before closing, so the underlying
		// connection can be reused by the Transport regardless of the
		// response status code. See https://github.com/ogen-go/ogen/issues/1670.
		_, _ = io.Copy(io.Discard, body)
		_ = body.Close()
	}()

	stage = "DecodeResponse"
	result, err := decodeSetServiceSharedResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// SetServiceSuspended invokes setServiceSuspended operation.
//
// Returns once the release is updated; its pods then stop or start in the background (Suspending,
// Deploying). Follow it with the service's event stream (watchServiceEvents).
//
// PUT /api/services/{releaseId}/suspended
func (c *Client) SetServiceSuspended(ctx context.Context, request *SetServiceSuspendedReq, params SetServiceSuspendedParams) (SetServiceSuspendedRes, error) {
	res, err := c.sendSetServiceSuspended(ctx, request, params)
	return res, err
}

func (c *Client) sendSetServiceSuspended(ctx context.Context, request *SetServiceSuspendedReq, params SetServiceSuspendedParams) (res SetServiceSuspendedRes, err error) {
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("setServiceSuspended"),
		semconv.HTTPRequestMethodKey.String("PUT"),
		semconv.URLTemplateKey.String("/api/services/{releaseId}/suspended"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, SetServiceSuspendedOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [3]string
	pathParts[0] = "/api/services/"
	{
		// Encode "releaseId" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "releaseId",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.ReleaseId))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/suspended"
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "PUT", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeSetServiceSuspendedRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	stage = "EncodeHeaderParams"
	h := uri.NewHeaderEncoder(r.Header)
	{
		cfg := uri.HeaderParameterEncodingConfig{
			Name:    "X-Onyxia-Project",
			Explode: false,
		}
		if err := h.EncodeParam(cfg, func(e uri.Encoder) error {
			return e.EncodeValue(conv.StringToString(params.XOnyxiaProject))
		}); err != nil {
			return res, errors.Wrap(err, "encode header")
		}
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{
			stage = "Security:Oidc"
			switch err := c.securityOidc(ctx, SetServiceSuspendedOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"Oidc\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer func() {
		// Drain the body to EOF before closing, so the underlying
		// connection can be reused by the Transport regardless of the
		// response status code. See https://github.com/ogen-go/ogen/issues/1670.
		_, _ = io.Copy(io.Discard, body)
		_ = body.Close()
	}()

	stage = "DecodeResponse"
	result, err := decodeSetServiceSuspendedResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// WatchServiceEvents invokes watchServiceEvents operation.
//
// Server-Sent Events (text/event-stream), one frame per event: "event: \ndata: \n\n" (see
// ServiceStreamEvent for the payload of each event). Open it after an install, suspend or resume,
// before a delete (once deleted, the service can no longer be opened), or when showing a service in a
// transitional status.
//
//   - The first event is a "status" with the current state, and a "quota" with the project's quota when
//     there is one. A reconnection simply starts again from the current state: there is no event id to
//     resume from.
//   - Then "status" is sent each time the service changes, "progress" for each step Kubernetes reports
//     (scheduling, image pull, start, probe failure...), and "quota" each time the project's quota
//     usage changes.
//   - The server ends the stream with "done" once the service is stable (Running, Suspended, an Error
//     with reason release_failed, or a Ghost that lasts: the release of a starting install appears a
//     moment after the service), deleted (no pod left), or after a maximum duration (15 minutes). Any
//     other Error keeps the stream open: a crash loop or an exceeded quota can resolve by itself.
//   - The stream may also end without "done" (server shutdown, broken watch): reopen it.
//   - A comment line (": keep-alive") is sent periodically so that proxies keep the connection open.
//
// The browser's native EventSource can't send the Authorization and X-Onyxia-Project headers: use a
// fetch-based SSE client.
//
// GET /api/services/{releaseId}/events
func (c *Client) WatchServiceEvents(ctx context.Context, params WatchServiceEventsParams) (WatchServiceEventsRes, error) {
	res, err := c.sendWatchServiceEvents(ctx, params)
	return res, err
}

func (c *Client) sendWatchServiceEvents(ctx context.Context, params WatchServiceEventsParams) (res WatchServiceEventsRes, err error) {
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("watchServiceEvents"),
		semconv.HTTPRequestMethodKey.String("GET"),
		semconv.URLTemplateKey.String("/api/services/{releaseId}/events"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, WatchServiceEventsOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [3]string
	pathParts[0] = "/api/services/"
	{
		// Encode "releaseId" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "releaseId",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.ReleaseId))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/events"
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	stage = "EncodeHeaderParams"
	h := uri.NewHeaderEncoder(r.Header)
	{
		cfg := uri.HeaderParameterEncodingConfig{
			Name:    "X-Onyxia-Project",
			Explode: false,
		}
		if err := h.EncodeParam(cfg, func(e uri.Encoder) error {
			return e.EncodeValue(conv.StringToString(params.XOnyxiaProject))
		}); err != nil {
			return res, errors.Wrap(err, "encode header")
		}
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{
			stage = "Security:Oidc"
			switch err := c.securityOidc(ctx, WatchServiceEventsOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"Oidc\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}

	stage = "DecodeResponse"
	result, err := decodeWatchServiceEventsResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}
