// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
	"net/http"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}
var _ RawHandler = UnimplementedHandler{}

// DeleteService implements deleteService operation.
//
// Runs helm uninstall for the release and removes the associated Onyxia secret. This operation is
// irreversible.
//
// DELETE /api/services/{releaseId}
func (UnimplementedHandler) DeleteService(ctx context.Context, params DeleteServiceParams) (r DeleteServiceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetMyCatalogs implements getMyCatalogs operation.
//
// Returns the list of catalogs and packages available for the user. The list of packages is filtered
// by user permissions if the user is authenticated. Otherwise returns the public catalog.
//
// GET /api/services/catalogs
func (UnimplementedHandler) GetMyCatalogs(ctx context.Context) (r GetMyCatalogsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetMyPackage implements getMyPackage operation.
//
// Returns detailed information about a package in a catalog, including available versions.
//
// GET /api/services/catalogs/{catalogId}/packages/{packageName}
func (UnimplementedHandler) GetMyPackage(ctx context.Context, params GetMyPackageParams) (r GetMyPackageRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPackageSchema implements getPackageSchema operation.
//
// Returns the values.schema.json of a versioned package. The schema is enhanced by user permissions
// and roles.
//
// GET /api/services/catalogs/{catalogId}/packages/{packageName}/versions/{version}/schema
func (UnimplementedHandler) GetPackageSchema(ctx context.Context, params GetPackageSchemaParams) (r GetPackageSchemaRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetProjectQuota implements getProjectQuota operation.
//
// Initial load only: while a service changes, its event stream pushes the quota updates.
//
// GET /api/services/project/quota
func (UnimplementedHandler) GetProjectQuota(ctx context.Context, params GetProjectQuotaParams) (r GetProjectQuotaRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetService implements getService operation.
//
// Get the current state of a service.
//
// GET /api/services/{releaseId}
func (UnimplementedHandler) GetService(ctx context.Context, params GetServiceParams) (r GetServiceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// InstallService implements installService operation.
//
// Starts an install for the given releaseId and returns 202 as soon as the package is resolved; the
// install goes on in the background. Follow it with the service's event stream (watchServiceEvents).
// The releaseId is reserved by the first install: a second install with the same releaseId gets 409,
// whether the first one is still running or done.
//
// PUT /api/services/{releaseId}
func (UnimplementedHandler) InstallService(ctx context.Context, req *ServiceInstallRequest, params InstallServiceParams) (r InstallServiceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListServices implements listServices operation.
//
// List all services in a project namespace.
//
// GET /api/services
func (UnimplementedHandler) ListServices(ctx context.Context, params ListServicesParams) (r ListServicesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SetServiceShared implements setServiceShared operation.
//
// Only the owner of the service may change this flag. Sharing requires the service's catalog to allow
// it.
//
// PUT /api/services/{releaseId}/shared
func (UnimplementedHandler) SetServiceShared(ctx context.Context, req *SetServiceSharedReq, params SetServiceSharedParams) (r SetServiceSharedRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SetServiceSuspended implements setServiceSuspended operation.
//
// Returns once the release is updated; its pods then stop or start in the background (Suspending,
// Deploying). Follow it with the service's event stream (watchServiceEvents).
//
// PUT /api/services/{releaseId}/suspended
func (UnimplementedHandler) SetServiceSuspended(ctx context.Context, req *SetServiceSuspendedReq, params SetServiceSuspendedParams) (r SetServiceSuspendedRes, _ error) {
	return r, ht.ErrNotImplemented
}

// WatchServiceEvents implements watchServiceEvents operation.
//
// Server-Sent Events (text/event-stream), one frame per event: "event: \ndata: \n\n" (see
// ServiceStreamEvent for the payload of each event). Open it after an install, suspend or resume,
// before a delete (once deleted, the service can no longer be opened), or when showing a service in a
// transitional status.
//
//   - The first event is a "status" with the current state, and a "quota" with the project's quota when
//     there is one. A reconnection simply starts again from the current state: there is no event id to
//     resume from.
//   - Then "status" is sent each time the service changes, "progress" for each step Kubernetes reports
//     (scheduling, image pull, start, probe failure...), and "quota" each time the project's quota
//     usage changes.
//   - The server ends the stream with "done" once the service is stable (Running, Suspended, an Error
//     with reason release_failed, or a Ghost that lasts: the release of a starting install appears a
//     moment after the service), deleted (no pod left), or after a maximum duration (15 minutes). Any
//     other Error keeps the stream open: a crash loop or an exceeded quota can resolve by itself.
//   - The stream may also end without "done" (server shutdown, broken watch): reopen it.
//   - A comment line (": keep-alive") is sent periodically so that proxies keep the connection open.
//
// The browser's native EventSource can't send the Authorization and X-Onyxia-Project headers: use a
// fetch-based SSE client.
//
// GET /api/services/{releaseId}/events
func (UnimplementedHandler) WatchServiceEvents(ctx context.Context, params WatchServiceEventsParams, w http.ResponseWriter) error {
	return ht.ErrNotImplemented
}
